config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  mount Starburst::Engine => "/starburst"

  # Handle API
  namespace :api do
    namespace :v1 do
      resources :urls, only: %i[create show update]
    end
  end

  # dev routes for cypress
  if Rails.env.development? || Rails.env.test?
    scope path: "/__cypress__", controller: "cypress" do
      post "login", action: "login"
    end
  end

  # Handle Auth
  post "/auth/:provider/callback", to: "sessions#create", as: 'auth_saml_callback'

  # omniauth developer provider uses a GET request
  if Rails.application.config.omniauth_provider == "developer"
    get "/auth/developer/callback", to: "sessions#create"
  end

  get 'auth/saml/metadata' => 'saml_metadata#metadata'

  root "home#index"
  get "shortener", to: "urls#index"

  get "/pages/:page" => "pages#show", :as => :pages

  # This will allow us to run the meat of the app at z.umn.edu/shortener and
  # assume that all other z.umn.edu/:keywords are requests for short urls.
  scope "/shortener" do
    # /	home	index	get
    get "/home", to: "home#index"

    # / user_lookup/:search_terms
    get "/user_lookup/:search_terms", to: "user_lookup#index"

    # faq	faq	index	get
    get "/faq", to: "faq#index", as: "faq"

    # sessions sessions destroy get
    get "/signin", to: "sessions#new"
    get "/signout", to: "sessions#destroy"

    # urls	urls	index	get
    # urls/:id	urls	show	get
    # urls/:id/edit	urls	edit	get
    # urls/new	urls	new	get
    # urls/update	urls	update	post
    # urls/create	urls	create	put
    # urls/destroy	urls	destroy	delete
    resources :urls do
      get "datatable", to: "urls_datatable#index", on: :collection
      get "keyword_filter/(:destination)/(:keyword)",
        on: :collection,
        to: "urls#keyword_filter",
        as: "keyword_filter"
      get "download_qrcode", to: "url_barcodes#show"
      get "csv/click_data", to: "url_csvs#show"
      get "csv/:duration/:time_unit", to: "url_csvs#show_aggregated"
      get "csv/:duration/:time_unit",
        on: :collection,
        to: "url_csvs#show_aggregated",
        as: "csv"
      member do
        patch :note, to: 'urls#update_note'
      end
      patch :note, on: :member, to: 'urls#update_note'
    end

    # transfer_requests	transfer_requests	index	get
    # transfer_requests/new	transfer_requests	new	post
    # transfer_requests/confirm	transfer_requests	confirm	post
    # transfer_requests/create	transfer_requests	create	put
    # transfer_requests/:id/:key/:status	transfer_requests	update	post
    # transfer_requests/:id/show	transfer_requests	show	get
    # transfer_requests/:id/edit	transfer_requests	edit	get
    # transfer_requests/:id/withdraw	transfer_requests	destroy	delete
    resources :transfer_requests do
      post "confirm", on: :member
    end

    resources :move_to_group, only: %i[new create]
    resources :batch_delete, only: %i[new create]

    # groups	groups	index	get
    # groups/:id	groups	show	get
    # groups/:id/edit	groups	edit	get
    # groups/new	groups	new	get
    # groups/update	groups	update	post
    # groups/create	groups	create	put
    # groups/destroy	groups	destroy	delete
    resources :groups do
      # groups/:id/members	group_memberships	index	get
      # groups/:id/members/new	group_memberships	new	get
      # groups/:id/members/create	group_memberships	create	put
      # groups/:id/members/destroy	group_memberships	destroy	delete
      resources :members, only: %i[index new create destroy], controller: "group_memberships" do
        get "new/:search_terms", to: "group_memberships#new", on: :collection
      end
    end

    # users/:id/show	user	show	put
    resources :users, only: [:show]
    resources :lookup_users, only: [:index]
    # api_keys	api_keys	index	get
    # api_keys/new	api_keys	new	get
    # api_keys/:id	api_keys	show	get
    # api_keys/:id/update	api_keys	update	post
    # api_keys/create	api_keys	create	put
    # api_keys/destroy	api_keys	destroy	delete
    resources :api_keys, only: %i[index create] do
      delete "delete", on: :collection
    end

    # group_context/update	group_context	show	get
    resources :group_context, only: [:show]

    namespace :admin do
      # admin/transfer_requests/	admin::transfer_requests	index	get
      # admin/transfer_requests/new	admin::transfer_requests	new	post
      # admin/transfer_requests/confirm	admin::transfer_requests	confirm	post
      # admin/transfer_requests/create	admin::transfer_requests	create	put
      # admin/transfer_requests/:id/show	admin::transfer_requests	show	get
      resources :transfer_requests, only: %i[index new create show] do
        post "confirm", on: :member
      end

      # admin/urls/:search	admin::urls	index	get
      # admin/urls/:id	admin::urls	show	get
      # admin/urls/update	admin::urls	update	post
      # admin/urls/delete	admin::urls	destroy	delete
      # admin/urls/create	admin::urls	create	put
      resources :urls, only: %i[index edit show update destroy create] do
        get "csv/:duration/:time_unit",
            on: :collection,
            to: "url_csvs#show",
            as: "csv"
      end

      # admin/audits/:search	admin::urls	index	get
      # admin/audits/:id	admin::urls	show	get
      resources :audits, only: [:index]

      # admin/groups
      # admin/groups/:id
      # admin/groups/:id/urls
      # admin/groups/:id/members
      resources :groups, only: %i[index show] do
        resources :urls, only: [:index], controller: "group_urls"
        resources :members, only: [:index], controller: "group_members"
      end

      # admin/members/:search	admin::members	index	get
      # admin/members/:id	admin::members	show	get
      # admin/members/delete	admin::members	destroy	delete
      # admin/members/create	admin::members	create	put
      resources :members, only: %i[index new create destroy], controller: "members" do
        get "new/:search_terms", to: "members#new", on: :collection
      end

      # admin/admins	admin::admins	index	get
      # admin/admins/delete	admin::admins	destroy	delete
      # admin/admins/create	admin::admins	create	put
      resources :admins, only: %i[index destroy create]

      resources :announcements, only: %i[index new edit show update destroy create]
    end
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # /:keyword	redirect index	get
  get "/*keyword", to: "redirect#index"
end

app/controllers/admin/urls_controller.rb
class Admin::UrlsController < ApplicationController
  before_action :set_url, only: %i[show edit update destroy]
  before_action :ensure_signed_in
  before_action :set_admin_view

  def index
    # Filter URLs based on keyword
    @urls = Url.by_keyword(params[:url_filter_keyword])
    authorize @urls unless @urls.nil?
    # If owner filter present, filter further
    @urls = @urls.created_by_name('params[:url_filter_owner]') if params[:url_filter_owner].present?

    respond_to do |format|
      format.html
      format.json { render json: AdminUrlDatatable.new(params, view_context:) }
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @url_identifier = @url.id
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def edit
    @url_identifier = @url.id
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.js   { render :update }
      else
        format.js   { render :edit }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js   { render 'urls/destroy', layout: false }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_url
    @url = Url.find(params[:id])
    authorize @url unless @url.nil?
    @url_identifier = @url.id
  end

  # Never trust parameters from the scary internet
  # only allow the allowlist through.
  def url_params
    params.require(:url).permit(:url, :keyword, :group_id, :modified_by, :duration, :time_unit)
  end
end

app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < Api::V1::BaseController
  def show
    # the `id` param actually the keyword
    keyword = params[:id]

    # get the url with the keyword
    url = Url.find_by(keyword:)

    # if there's no url, return 404
    if url.blank?
      render json: { status: :error, message: 'URL not found' }, status: :not_found
      return
    end

    # if the url's group doesn't have the current user as a member
    # then return 403
    if url.group.users.exclude?(@current_user)
      render json: { status: :error, message: 'Unauthorized access' }, status: :forbidden
      return
    end

    render json: { status: :success, message: url }
  end

  def create
    urls = @payload['urls']

    urls.each do |url|
      # Find group_id to use for new URL
      if url['collection']
        group_id = @current_user.groups.find_by(name: url['collection']).try(:id)
        if group_id.blank?
          url['result'] = { status: :error, message: 'Cannot find collection with that name.' }
          next
        end
      else
        group_id = @current_user.default_group_id
      end

      new_url = Url.new(url: url['url'], keyword: url['keyword'], group_id:)

      url['result'] =
        if new_url.save
          { status: :success, message: view_context.full_url(new_url) }
        else
          { status: :error, message: new_url.errors.full_messages }
        end
    end

    render json: urls
  end

  def update
    current_keyword = params[:id]

    url = Url.find_by(keyword: current_keyword)

    # if there's no url, return 404
    if url.blank?
      render json: { status: :error, message: 'URL not found' }, status: :not_found
      return
    end

    # if the url's group doesn't have the current user as a member
    # then return 403
    if url.group.users.exclude?(@current_user)
      render json: { status: :error, message: 'Unauthorized access' }, status: :forbidden
      return
    end

    # don't permit keyword changes
    if @payload['keyword'] && @payload['keyword'] != current_keyword
      render json: { status: :error, message: 'Cannot change keyword' }, status: :bad_request
      return
    end

    # update url with payload
    url.url = @payload['url']
    url.save

    render json: { status: :success, message: url }
  end
end

app/controllers/urls_controller.rb
# controllers/url_controller.rb
class UrlsController < ApplicationController
  before_action :ensure_signed_in
  before_action :set_url, only: %i[edit update destroy]
  before_action :set_url_friendly, only: %i[show update_note]
  before_action :set_group, only: %i[index create]

  # GET /urls
  # GET /urls.json
  def index
    group_ids_to_get = if @group == current_user.context_group
                         current_user.groups.pluck(:id)
                       else
                         [@group.id]
                       end

    # NOTE: the table is actually populated by datatables,
    # so this doesn't really have any visible effect
    @urls = Url.created_by_ids(group_ids_to_get)
               .not_in_pending_transfer_request

    @pending_transfer_requests_to =
      TransferRequest.pending.where(to_group_id: @group.id)

    @pending_transfer_requests_from =
      TransferRequest.pending
                     .where(from_group_id: @group.id)
    @url = Url.new(group_id: @group.id)
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @url_identifier = @url.id

    @clicks = {
      hrs24:
        @url.clicks.group_by_time_ago(24.hours, '%I:%M%p'),
      days7:
        @url.clicks.group_by_time_ago(7.days, '%m/%d'),
      days30:
        @url.clicks.group_by_time_ago(30.days, '%m/%d'),
      alltime:
        @url.clicks.group_by_time_ago(
          ((Time.zone.now - @url.created_at) / 60 / 60 / 24).ceil.days,
          '%m/%Y'
        ),
      regions:
        @url.clicks.group(:country_code).count.to_a
    }

    @best_day = @url.clicks.max_by_day

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # GET /urls/new
  def new
    @url = Url.new
    @url_identifier = Time.zone.now.to_ms
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def edit
    @url_identifier = @url.id

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # POST /urls
  # POST /urls.json
  def create
    @url_identifier = params[:new_identifier]
    @url = Url.new(url_params)
    @url.group = @group

    # reset the form using the same group
    @empty_url = Url.new(group: @group)

    respond_to do |format|
      if @url.save
        format.html do
          redirect_to urls_path, notice: 'URL was successfully created.'
        end
        format.js { render :create }
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.js   { render :update }
        format.json { render json: @url }
      else
        format.js   { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT/PATCH /urls/1/note
  def update_note
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to url_path(@url.keyword), notice: 'Note saved.' }
      else
        flash[:error] = @url.errors.full_messages.join(', ')
        format.html { redirect_to url_path(@url.keyword) }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    if @url.destroy
      respond_to do |format|
        format.html { redirect_to urls_url, notice: 'URL was successfully destroyed.' }
        format.js { render layout: false }
        format.json { render json: { success: true, message: "Group deleted." } }
      end
    else
      respond_to do |format|
        format.html { redirect_to urls_url, notice: 'URL could not be deleted.' }
        format.js   { render layout: false }
        format.json { render json: { success: false, errors: @group.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # GET /urls/:keyword/:destination
  # Get /urls/ryan/transfer_request
  def keyword_filter
    @keyword = params[:keyword]
    @destination = params[:destination]
    @urls = Url
            .by_keyword(@keyword)
            .created_by_id(current_user.context_group_id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_url
    @url = Url.find(params[:id])
    raise ActiveRecord::RecordNotFound if @url.nil?

    authorize @url unless @url.nil?
    @url_identifier = @url.id
  end

  def set_url_friendly
    @url = Url.find_by(keyword: params[:id])
    raise ActiveRecord::RecordNotFound if @url.nil?

    authorize @url unless @url.nil?
    @url_identifier = @url.id
  end

  # Never trust parameters from the scary internet,
  # only permit the allowlist through.
  def url_params
    params.require(:url).permit(:url, :keyword, :group_id, :modified_by, :note)
  end

  def set_group
    # use collection query string if present,
    # or the url's group_id if present.
    # otherwise use current_user's context_group_id
    group_id = params[:collection].presence || params.dig(:url, :group_id) || current_user.context_group_id
    @group = Group.find(group_id)

    authorize @group, :update?
  rescue Pundit::NotAuthorizedError
    redirect_to urls_path, alert: "You do not have permission to access this collection. Redirected to your Z-Links."
  end
end

app/helpers/url_helper.rb
module UrlHelper
  def full_url(url)
    "#{request.base_url}/#{url.keyword}"
  end

  def display_long_url(url, max_length = 20)
    truncate(url, length: max_length)
  end

  def display_keyword_url(keyword, _max_length = 35)
    # "#{request.host_with_port}/#{truncate(keyword, length: max_length)}"
    "#{request.host_with_port}/#{keyword}"
  end

  def best_day_formatter(best_day)
    if best_day.blank?
      t('views.urls.show.best_day', count: 0)
    else
      t(
        'views.urls.show.best_day',
        count: best_day[1],
        date: best_day[0].strftime('%B %d %Y')
      )
    end
  end
end

app/views/urls/_share_buttons.html.erb
<% 
  is_large = (defined?(large) && large == true) ? 'btn-lg' : 'btn-sm' 
%>
<button class="btn btn-default tw-border-twitter-blue tw-text-twitter-blue js-share-button-twitter hover:tw-bg-twitter-blue hover:tw-text-white hover:tw-border-twitter-blue <%= is_large %>" data-short-url="<%= full_url(url) %>">
  <i class="fa fa-twitter"></i>
  <%= t('views.urls.index.table.in_row_actions.tweet') %>
</button>
<!-- QR Code split download button -->
<div class="btn-group">
  <a href="<%= url_download_qrcode_path(url.keyword) %>" class="btn btn-default <%= is_large %> " download>
    <i class="fa fa-qrcode"></i>
    <%= t('views.urls.index.table.in_row_actions.qr_code') %>
  </a>
  <button type="button" class="btn btn-default dropdown-toggle  <%= is_large %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li>
      <a href="<%= url_download_qrcode_path(url.keyword) %>" download class="!tw-flex tw-justify-between tw-items-baseline">
        PNG 
        <span class="tw-uppercase tw-text-[0.75em] tw-text-neutral-400">Standard</span>
      </a>
    </li>
    <li>
      <a href="<%= url_download_qrcode_path(url.keyword, format: :svg) %>" download class="!tw-flex tw-justify-between tw-items-baseline">
        SVG 
        <span class="tw-uppercase tw-text-[0.75em] tw-text-neutral-400">Advanced</span>
      </a>
    </li>
  </ul>
</div>

app/views/urls/_transfer_requests_from.html.erb
<% if @pending_transfer_requests_from.present? %>
    <div class="bs-callout bs-callout-warning" id="callout-badges-ie8-empty">
      <h4><%= t('views.urls.index.transfer_requests.to_others')%> </h4>
      <p>
        <% @pending_transfer_requests_from.each do |transfer_request| %>
          <div class="transfer-request-item">
            <div class="transfer-details">
              <div class="to">
                <%= t('views.urls.index.transfer_requests.to_html', user: transfer_request.to_user.internet_id) %>
              </div>
              <% transfer_request.urls.each do |url| %>
                <div class="keyword">
                  <%= t('views.urls.index.transfer_requests.keyword_html', keyword: url.keyword) %>
                </div>
                <div class="url">
                  <%= t('views.urls.index.transfer_requests.url_html', url: link_to(url.url, url.url, target: 'blank')) %>
                </div>
              <% end %>
            </div>
            <a href="<%= transfer_request_path(transfer_request) %>" data-method="delete" data-confirm="<%= t('views.urls.index.transfer_requests.take_back_confirm') %>" class='btn btn-default btn-xs'><%= t('views.urls.index.transfer_requests.take_back') %></a>
          </div>
        <% end %>
      </p>
    </div>
<% end %>

app/views/urls/_transfer_requests_to.html.erb
<% if @pending_transfer_requests_to.present? %>
    <div class="bs-callout bs-callout-primary" id="callout-badges-ie8-empty">
      <h4><%= t('views.urls.index.transfer_requests.to_user')%> </h4>
      <p>
        <% @pending_transfer_requests_to.each do |transfer_request| %>
        <div class="transfer-request-item">
          <div class="transfer-details">
            <div class="to">
              <%= t('views.urls.index.transfer_requests.from_html', user: transfer_request.from_user.internet_id) %>
            </div>
            <% transfer_request.urls.each do |url| %>
              <div class="keyword">
                  <%= t('views.urls.index.transfer_requests.keyword_html', keyword: url.keyword) %>
              </div>
              <div class="url">
                  <%= t('views.urls.index.transfer_requests.url_html', url: link_to(url.url, url.url, target: 'blank')) %>
              </div>
            <% end %>
          </div>

          <a href="<%= transfer_request_path(transfer_request) %>" data-method="delete" data-confirm="<%= t('views.urls.index.transfer_requests.reject_confirm') %>" class='btn btn-default btn-xs js-reject-transfer'><%= t('views.urls.index.transfer_requests.reject') %></a>
          <a href="<%= confirm_transfer_request_path(transfer_request) %>" data-method="post" class='btn btn-primary btn-xs js-approve-transfer'><%= t('views.urls.index.transfer_requests.approve') %></a>
        </div>
        <% end %>
      </p>
    </div>
<% end %>

app/views/urls/destroy.js.erb
$('table.data-table').DataTable().draw();

app/views/urls/show.html.erb
<div class="page-header tw-text-center">
  <p class="tw-uppercase tw-tracking-wide tw-font-bold tw-text-center tw-text-sm tw-text-neutral-400">Z-Link Stats</p>
  <h1><%= @url.keyword %></h1>
</div>
<div class="tw-p-4">
  <div class="umn-post-it">
    <div class="row">
      <div class="col-md-7">
        <div class="row">
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading"><%= t('views.urls.show.short_url') %></div>
              <div class="panel-body">
                <a target='_blank' href="<%= full_url(@url) %>"><%= full_url(@url) %></a>
                <button class='btn btn-default clipboard-btn' data-clipboard-text="<%= full_url(@url) %>" data-cy="copy-button">
                  <i class=" fa fa-files-o"></i>
                  <%= t('views.urls.show.thing.copy') %>
                </button>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading"><%= t('views.urls.show.source_url') %></div>
              <div class="panel-body">
                <a target='_blank' href="<%= @url.url %>"><%= @url.url %></a>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 stats-actions">
            <div class="panel panel-default">
              <div class="panel-heading"><%= t('views.urls.show.collection') %></div>
              <div class="panel-body">
                <% user_groups_for_collection = group_names_and_ids_for_select(current_user.groups)%>
                <%= select_tag(
              "url-collection-#{@url.id}",
              options_for_select(
                user_groups_for_collection,
                @url.group_id
              ),
              class: 'form-control selectpicker collection-picker ',
              data: {
                update_path: url_path(@url.id),
                keyword: @url.keyword,
                group_id: @url.group_id
              }
            ) %>
              </div>
            </div>
            <button class="btn btn-primary js-transfer-urls ">
              <i class="fa fa-exchange"></i>
              <%= t('views.urls.transfer_button') %>
            </button>
          </div>
        </div>
        <div class="traffic-stats-header">
          <h3 ><%= t('views.urls.show.traffic_stats') %></h3>
          <a class='btn btn-default js-csv-download' href="<%= url_csv_click_data_path(@url, format: :csv) %>"><%= t('views.urls.show.export_button') %></a>
        </div>
        <div class="row">
          <div class="col-md-12">
            <ul id='show-tabs' class="col-md-12 nav nav-tabs" role='tablist'>
              <li role="presentation" class="active"><a href="#chart-div-hrs24" data-load='hrs24' data-toggle='tab' role='tab'><%= t('views.urls.show.hours_24')%></a></li>
              <li role="presentation"><a href="#chart-div-days7" data-load='days7' data-toggle='tab' role='tab'><%= t('views.urls.show.days_7')%></a></li>
              <li role="presentation"><a href="#chart-div-days30" data-load='days30' data-toggle='tab' role='tab'><%= t('views.urls.show.days_30')%></a></li>
              <li role="presentation"><a href="#chart-div-all" data-load='all' data-toggle='tab' role='tab'><%= t('views.urls.show.all_time')%></a></li>
            </ul>
            <div class="col-md-12 tab-content">
              <div role="tabpanel" class='tab-pane fade in active' id="chart-div-hrs24" ></div>
              <div role="tabpanel" class='tab-pane fade' id="chart-div-days7"></div>
              <div role="tabpanel" class='tab-pane fade' id="chart-div-days30"></div>
              <div role="tabpanel" class='tab-pane fade' id="chart-div-all"></div>
            </div>
          </div>
        </div>
        <h3><%= t('views.urls.show.traffic_location')%></h3>
        <div class="row">
          <div id="regions-div" class="col-md-12">
          </div>
        </div>
        <div class="row">
          <div id="regions-pie-div" class="col-md-12">
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">Note</div>
              <div class="panel-body text-center">
                <%= form_with model: @url, url: note_url_path(@url.keyword), method: :patch, data: { cy: 'note-form' } do |form|%>
                  <%= form.label :note, "Note", class: 'sr-only' %>
                  <%= form.text_area :note, class: 'form-control', placeholder: 'Add a note', data: { cy: 'note-input' } %>
                  <div class="tw-mt-2 tw-flex tw-justify-end tw-gap-2 tw-items-center">
                    <%= button_tag 'Reset', type: 'reset', class: "tw-uppercase tw-text-xs tw-bg-neutral-100 tw-px-4 tw-py-2 tw-rounded hover:tw-bg-neutral-200 tw-transition" %>
                    <%= form.button "Save", class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading"><%= t('views.urls.show.share') %></div>
              <div class="panel-body text-center">
                <%= render "/urls/share_buttons", url: @url, large: true %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading"><%= t('views.urls.show.historical_click_count') %></div>
              <div class="panel-body">
                <%= t('views.urls.show.created_on')%> <%= @url.created_at.to_fs(:created_on_formatted) %> (<%= time_ago_in_words(@url.created_at) %> ago)
              </div>
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <td><%= t('views.urls.show.hours_24')%></td>
                    <td><%= pluralize(@clicks[:hrs24].values.sum, 'hit') %></td>
                    <td><%= (@clicks[:hrs24].values.sum / 24.00).round(2) %> <%= t('views.urls.show.per_hour') %></td>
                  </tr>
                  <tr>
                    <td><%= t('views.urls.show.days_7')%></td>
                    <td><%= pluralize(@clicks[:days7].values.sum, 'hit') %></td>
                    <td><%= (@clicks[:days7].values.sum / 7.00).round(2) %> <%= t('views.urls.show.per_day') %></td>
                  </tr>
                  <tr>
                    <td><%= t('views.urls.show.days_30')%></td>
                    <td><%= pluralize(@clicks[:days30].values.sum, 'hit') %></td>
                    <td><%= (@clicks[:days30].values.sum / 30.0).round(2) %> <%= t('views.urls.show.per_day') %></td>
                  </tr>
                  <tr>
                    <td><%= t('views.urls.show.all_time')%></td>
                    <td><%= pluralize(@url.total_clicks, 'hit') %></td>
                    <td><%= (@url.total_clicks / ((Time.now.to_ms - @url.created_at.to_ms) / 1000 / 60 / 60 / 24.0).ceil).round(2) %> <%= t('views.urls.show.per_day') %></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading"><%= t('views.urls.show.best_day_header')%></div>
              <div class="panel-body">
                <%= best_day_formatter(@best_day) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'modal' %>
<script type="text/javascript">
  // Load the data functions for the Google Charts
  <%= render partial: 'urls/show_js/hrs24', formats: :js %>
  <%= render partial: 'urls/show_js/days7', formats: :js %>
  <%= render partial: 'urls/show_js/days30', formats: :js %>
  <%= render partial: 'urls/show_js/alltime', formats: :js %>
  <%= render partial: 'urls/show_js/country_map', formats: :js %>
  <%= render partial: 'urls/show_js/country_pie', formats: :js %>
  <%= render partial: 'urls/show_js/move', formats: :js %>
  <%= render partial: 'urls/show_js/transfer', formats: :js %>
</script>