config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  mount Starburst::Engine => "/starburst"

  # Handle API
  namespace :api do
    namespace :v1 do
      resources :urls, only: %i[create show update]
    end
  end

  # dev routes for cypress
  if Rails.env.development? || Rails.env.test?
    scope path: "/__cypress__", controller: "cypress" do
      post "login", action: "login"
    end
  end

  # Handle Auth
  post "/auth/:provider/callback", to: "sessions#create", as: 'auth_saml_callback'

  # omniauth developer provider uses a GET request
  if Rails.application.config.omniauth_provider == "developer"
    get "/auth/developer/callback", to: "sessions#create"
  end

  get 'auth/saml/metadata' => 'saml_metadata#metadata'

  root "home#index"
  get "shortener", to: "urls#index"

  get "/pages/:page" => "pages#show", :as => :pages

  # This will allow us to run the meat of the app at z.umn.edu/shortener and
  # assume that all other z.umn.edu/:keywords are requests for short urls.
  scope "/shortener" do
    # /	home	index	get
    get "/home", to: "home#index"

    # / user_lookup/:search_terms
    get "/user_lookup/:search_terms", to: "user_lookup#index"

    # faq	faq	index	get
    get "/faq", to: "faq#index", as: "faq"

    # sessions sessions destroy get
    get "/signin", to: "sessions#new"
    get "/signout", to: "sessions#destroy"

    # urls	urls	index	get
    # urls/:id	urls	show	get
    # urls/:id/edit	urls	edit	get
    # urls/new	urls	new	get
    # urls/update	urls	update	post
    # urls/create	urls	create	put
    # urls/destroy	urls	destroy	delete
    resources :urls do
      get "datatable", to: "urls_datatable#index", on: :collection
      get "keyword_filter/(:destination)/(:keyword)",
        on: :collection,
        to: "urls#keyword_filter",
        as: "keyword_filter"
      get "download_qrcode", to: "url_barcodes#show"
      get "csv/click_data", to: "url_csvs#show"
      get "csv/:duration/:time_unit", to: "url_csvs#show_aggregated"
      get "csv/:duration/:time_unit",
        on: :collection,
        to: "url_csvs#show_aggregated",
        as: "csv"
      member do
        patch :note, to: 'urls#update_note'
      end
      patch :note, on: :member, to: 'urls#update_note'
    end

    # transfer_requests	transfer_requests	index	get
    # transfer_requests/new	transfer_requests	new	post
    # transfer_requests/confirm	transfer_requests	confirm	post
    # transfer_requests/create	transfer_requests	create	put
    # transfer_requests/:id/:key/:status	transfer_requests	update	post
    # transfer_requests/:id/show	transfer_requests	show	get
    # transfer_requests/:id/edit	transfer_requests	edit	get
    # transfer_requests/:id/withdraw	transfer_requests	destroy	delete
    resources :transfer_requests do
      post "confirm", on: :member
    end

    resources :move_to_group, only: %i[new create]
    resources :batch_delete, only: %i[new create]

    # groups	groups	index	get
    # groups/:id	groups	show	get
    # groups/:id/edit	groups	edit	get
    # groups/new	groups	new	get
    # groups/update	groups	update	post
    # groups/create	groups	create	put
    # groups/destroy	groups	destroy	delete
    resources :groups do
      # groups/:id/members	group_memberships	index	get
      # groups/:id/members/new	group_memberships	new	get
      # groups/:id/members/create	group_memberships	create	put
      # groups/:id/members/destroy	group_memberships	destroy	delete
      resources :members, only: %i[index new create destroy], controller: "group_memberships" do
        get "new/:search_terms", to: "group_memberships#new", on: :collection
      end
    end

    # users/:id/show	user	show	put
    resources :users, only: [:show]
    resources :lookup_users, only: [:index]
    # api_keys	api_keys	index	get
    # api_keys/new	api_keys	new	get
    # api_keys/:id	api_keys	show	get
    # api_keys/:id/update	api_keys	update	post
    # api_keys/create	api_keys	create	put
    # api_keys/destroy	api_keys	destroy	delete
    resources :api_keys, only: %i[index create] do
      delete "delete", on: :collection
    end

    # group_context/update	group_context	show	get
    resources :group_context, only: [:show]

    namespace :admin do
      # admin/transfer_requests/	admin::transfer_requests	index	get
      # admin/transfer_requests/new	admin::transfer_requests	new	post
      # admin/transfer_requests/confirm	admin::transfer_requests	confirm	post
      # admin/transfer_requests/create	admin::transfer_requests	create	put
      # admin/transfer_requests/:id/show	admin::transfer_requests	show	get
      resources :transfer_requests, only: %i[index new create show] do
        post "confirm", on: :member
      end

      # admin/urls/:search	admin::urls	index	get
      # admin/urls/:id	admin::urls	show	get
      # admin/urls/update	admin::urls	update	post
      # admin/urls/delete	admin::urls	destroy	delete
      # admin/urls/create	admin::urls	create	put
      resources :urls, only: %i[index edit show update destroy create] do
        get "csv/:duration/:time_unit",
            on: :collection,
            to: "url_csvs#show",
            as: "csv"
      end

      # admin/audits/:search	admin::urls	index	get
      # admin/audits/:id	admin::urls	show	get
      resources :audits, only: [:index]

      # admin/groups
      # admin/groups/:id
      # admin/groups/:id/urls
      # admin/groups/:id/members
      resources :groups, only: %i[index show] do
        resources :urls, only: [:index], controller: "group_urls"
        resources :members, only: [:index], controller: "group_members"
      end

      # admin/members/:search	admin::members	index	get
      # admin/members/:id	admin::members	show	get
      # admin/members/delete	admin::members	destroy	delete
      # admin/members/create	admin::members	create	put
      resources :members, only: %i[index new create destroy], controller: "members" do
        get "new/:search_terms", to: "members#new", on: :collection
      end

      # admin/admins	admin::admins	index	get
      # admin/admins/delete	admin::admins	destroy	delete
      # admin/admins/create	admin::admins	create	put
      resources :admins, only: %i[index destroy create]

      resources :announcements, only: %i[index new edit show update destroy create]
    end
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # /:keyword	redirect index	get
  get "/*keyword", to: "redirect#index"
end

app/controllers/group_memberships_controller.rb
class GroupMembershipsController < ApplicationController
  before_action :set_params, only: %i[index create destroy]
  before_action :ensure_signed_in

  def index; end

  def new
    render json: UserLookup.new(
      query: params[:search_terms],
      query_type: "all"
    ).search
  end

  def create
    member = User.find_or_create_by(uid: params["uid"])
    @group.add_user(member)
    respond_to do |format|
      if @group.user?(member)
        # rubocop: disable Rails/RenderInline
        format.js { render inline: "location.reload();" }
        format.json do
          render json: group_member_as_json(member), status: :created,
                 location: group_members_url(@group)
        end
        # rubocop: enable Rails/RenderInline
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @member = User.find(params[:id])
    @group.remove_user(@member)
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully updated, user removed." }
      format.json { head :no_content }
      format.js { render layout: false }
    end
  end

  private

  def group_member_as_json(member)
    {
      id: member.id,
      uid: member.uid,
      display_name: member.display_name,
      internet_id: member.internet_id,
      email: member.email,
      admin: member.admin,
      created_at: member.created_at,
      updated_at: member.updated_at
    }
  end

  def set_params
    @group = Group.find(params[:group_id])
    authorize @group unless @group.nil?
    @group_identifier = @group.id
    @members = @group.users
  end

  def user_params
    params.permit(:uid)
  end
end

app/views/group_memberships/_form.html.erb
<div id="search">
  <%= form_tag(group_members_path, remote: true, method: 'post', id: 'search-form', class: 'new_member') do %>
    <div class="input-wrapper new-member-wrapper">
      <%= label_tag :people_search, t('views.group_memberships.index.form.add_someone') %>
      <%= text_field_tag 'people_search', nil, class: 'form-control', required: true %>
      <span id="searchHelpInline" class="text-muted">
        <%= t('views.group_memberships.index.form.help') %>.
      </span>
      <span class="hidden glyphicon glyphicon-refresh glyphicon-refresh-animate" aria-hidden="true"></span>
      <%= hidden_field_tag 'uid' %>
    </div>
      <%= button_tag type: "submit", class: 'btn btn-primary add-new-group-member', data: { confirm: t('views.group_memberships.index.form.submit_confirm') } do %>
        <i class="fa fa-plus-circle"></i>
  <%= t('views.group_memberships.index.form.submit') %>
      <% end %>
  <% end %>
</div>

app/views/group_memberships/_in_row_search_results.html.erb
<tr id='result-<%= result.id %>'>
  <td><%= result.user_full_name %></td>
  <td><%= result.uid %></td>
  <td><%= result.admin %></td>
  <td><%= l result.created_at %></td>

  <td>
    <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                group_member_path(@group, member),
                :method => :delete,
                :data => {confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?'))},
                class: 'btn btn-xs btn-danger delete-group-member', remote: true %>
  </td>
</tr>

app/views/group_memberships/_in_row_show.html.erb
<tr id='user-<%= member.id %>'>
  <td><%= member.display_name %></td>
  <% if member.email %>
      <td><%= member.email %></td>
  <% else %>
      <td><i><%= t('views.group_memberships.index.table.no_email') %> </i></td>
  <% end %>
  <td>
    <%= link_to t('views.group_memberships.index.table.destroy'),
                group_member_path(@group, member),
                method: :delete,
                data: { confirm: t('views.group_memberships.index.table.destroy_confirm', to_delete: member.display_name) },
                class: 'btn btn-xs btn-danger delete-group-member fa fa-trash-o', remote: true %>
  </td>
</tr>

app/views/group_memberships/destroy.js.erb
$(document).find("tr#user-<%= @member.id %>").remove();

app/views/group_memberships/index.html.erb
<script type="text/javascript">
  $(function () {
      var peopleSearch = new Bloodhound({
          datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
          queryTokenizer: Bloodhound.tokenizers.whitespace,
          remote: {
              url: "<%= request.base_url %>/shortener/groups/<%= @group.id %>/members/new/%QUERY",
              wildcard: '%QUERY'
          }
      });

      $('#people_search').typeahead({minLength: 2}, {
          name: 'people_search',
          limit: 10,
          display: 'display',
          source: peopleSearch,
          templates: {
            empty: [
              '<div class="tt-suggestion empty-message">',
                '<p>' + I18n.t('views.transfer_requests.new.no_users_found') + '</p>',
              '</div>'
            ].join('\n'),
            suggestion: function(data){
              return [
                '<div>',
                '<p class="autocompleter-name"><strong>' + data.display_name + '</strong></p><p>'+ data.internet_id +'</p>',
                '</div>'].join('\n')
            }
          }
      })
      .on('typeahead:asyncrequest', function() {
        $('.glyphicon-refresh').removeClass("hidden");
      })
      .on('typeahead:asynccancel typeahead:asyncreceive', function() {
        $('.glyphicon-refresh').addClass("hidden");
      });;

      $('#people_search').bind('typeahead:selected', function (obj, datum, name) {
          $("#uid").val(datum.umndid);
      });

  });
</script>
<div class="z-hero z-hero-dimmer">
  <div class="z-hero-content">
    <div class="page-header">
      <h1><%= t('views.group_memberships.index.title_html', group_name: @group.name) %></h1>
    </div>
  </div>
</div>
<div class="tw-p-4">
  <div class="umn-post-it">
    <div id="new-member-form">
      <%= render 'form' %>
    </div>
    <table id="members-table" class="table user-table table-striped table-bordered data-table">
      <thead>
        <tr>
          <th><%= t('views.group_memberships.index.table.member_name')%></th>
          <th><%= t('views.group_memberships.index.table.email')%></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @members.each do |member| %>
          <%= render 'in_row_show', member: member, group: @group %>
        <% end %>
      </tbody>
    </table>
    <%= link_to groups_path do %>
      <i class="fa fa-arrow-circle-left"></i>
      <%= t('views.group_memberships.index.back_to_collections') %>
    <% end %>
  </div>
</div>