config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  mount Starburst::Engine => "/starburst"

  # Handle API
  namespace :api do
    namespace :v1 do
      resources :urls, only: %i[create show update]
    end
  end

  # dev routes for cypress
  if Rails.env.development? || Rails.env.test?
    scope path: "/__cypress__", controller: "cypress" do
      post "login", action: "login"
    end
  end

  # Handle Auth
  post "/auth/:provider/callback", to: "sessions#create", as: 'auth_saml_callback'

  # omniauth developer provider uses a GET request
  if Rails.application.config.omniauth_provider == "developer"
    get "/auth/developer/callback", to: "sessions#create"
  end

  get 'auth/saml/metadata' => 'saml_metadata#metadata'

  root "home#index"
  get "shortener", to: "urls#index"

  get "/pages/:page" => "pages#show", :as => :pages

  # This will allow us to run the meat of the app at z.umn.edu/shortener and
  # assume that all other z.umn.edu/:keywords are requests for short urls.
  scope "/shortener" do
    # /	home	index	get
    get "/home", to: "home#index"

    # / user_lookup/:search_terms
    get "/user_lookup/:search_terms", to: "user_lookup#index"

    # faq	faq	index	get
    get "/faq", to: "faq#index", as: "faq"

    # sessions sessions destroy get
    get "/signin", to: "sessions#new"
    get "/signout", to: "sessions#destroy"

    # urls	urls	index	get
    # urls/:id	urls	show	get
    # urls/:id/edit	urls	edit	get
    # urls/new	urls	new	get
    # urls/update	urls	update	post
    # urls/create	urls	create	put
    # urls/destroy	urls	destroy	delete
    resources :urls do
      get "datatable", to: "urls_datatable#index", on: :collection
      get "keyword_filter/(:destination)/(:keyword)",
        on: :collection,
        to: "urls#keyword_filter",
        as: "keyword_filter"
      get "download_qrcode", to: "url_barcodes#show"
      get "csv/click_data", to: "url_csvs#show"
      get "csv/:duration/:time_unit", to: "url_csvs#show_aggregated"
      get "csv/:duration/:time_unit",
        on: :collection,
        to: "url_csvs#show_aggregated",
        as: "csv"
      member do
        patch :note, to: 'urls#update_note'
      end
      patch :note, on: :member, to: 'urls#update_note'
    end

    # transfer_requests	transfer_requests	index	get
    # transfer_requests/new	transfer_requests	new	post
    # transfer_requests/confirm	transfer_requests	confirm	post
    # transfer_requests/create	transfer_requests	create	put
    # transfer_requests/:id/:key/:status	transfer_requests	update	post
    # transfer_requests/:id/show	transfer_requests	show	get
    # transfer_requests/:id/edit	transfer_requests	edit	get
    # transfer_requests/:id/withdraw	transfer_requests	destroy	delete
    resources :transfer_requests do
      post "confirm", on: :member
    end

    resources :move_to_group, only: %i[new create]
    resources :batch_delete, only: %i[new create]

    # groups	groups	index	get
    # groups/:id	groups	show	get
    # groups/:id/edit	groups	edit	get
    # groups/new	groups	new	get
    # groups/update	groups	update	post
    # groups/create	groups	create	put
    # groups/destroy	groups	destroy	delete
    resources :groups do
      # groups/:id/members	group_memberships	index	get
      # groups/:id/members/new	group_memberships	new	get
      # groups/:id/members/create	group_memberships	create	put
      # groups/:id/members/destroy	group_memberships	destroy	delete
      resources :members, only: %i[index new create destroy], controller: "group_memberships" do
        get "new/:search_terms", to: "group_memberships#new", on: :collection
      end
    end

    # users/:id/show	user	show	put
    resources :users, only: [:show]
    resources :lookup_users, only: [:index]
    # api_keys	api_keys	index	get
    # api_keys/new	api_keys	new	get
    # api_keys/:id	api_keys	show	get
    # api_keys/:id/update	api_keys	update	post
    # api_keys/create	api_keys	create	put
    # api_keys/destroy	api_keys	destroy	delete
    resources :api_keys, only: %i[index create] do
      delete "delete", on: :collection
    end

    # group_context/update	group_context	show	get
    resources :group_context, only: [:show]

    namespace :admin do
      # admin/transfer_requests/	admin::transfer_requests	index	get
      # admin/transfer_requests/new	admin::transfer_requests	new	post
      # admin/transfer_requests/confirm	admin::transfer_requests	confirm	post
      # admin/transfer_requests/create	admin::transfer_requests	create	put
      # admin/transfer_requests/:id/show	admin::transfer_requests	show	get
      resources :transfer_requests, only: %i[index new create show] do
        post "confirm", on: :member
      end

      # admin/urls/:search	admin::urls	index	get
      # admin/urls/:id	admin::urls	show	get
      # admin/urls/update	admin::urls	update	post
      # admin/urls/delete	admin::urls	destroy	delete
      # admin/urls/create	admin::urls	create	put
      resources :urls, only: %i[index edit show update destroy create] do
        get "csv/:duration/:time_unit",
            on: :collection,
            to: "url_csvs#show",
            as: "csv"
      end

      # admin/audits/:search	admin::urls	index	get
      # admin/audits/:id	admin::urls	show	get
      resources :audits, only: [:index]

      # admin/groups
      # admin/groups/:id
      # admin/groups/:id/urls
      # admin/groups/:id/members
      resources :groups, only: %i[index show] do
        resources :urls, only: [:index], controller: "group_urls"
        resources :members, only: [:index], controller: "group_members"
      end

      # admin/members/:search	admin::members	index	get
      # admin/members/:id	admin::members	show	get
      # admin/members/delete	admin::members	destroy	delete
      # admin/members/create	admin::members	create	put
      resources :members, only: %i[index new create destroy], controller: "members" do
        get "new/:search_terms", to: "members#new", on: :collection
      end

      # admin/admins	admin::admins	index	get
      # admin/admins/delete	admin::admins	destroy	delete
      # admin/admins/create	admin::admins	create	put
      resources :admins, only: %i[index destroy create]

      resources :announcements, only: %i[index new edit show update destroy create]
    end
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # /:keyword	redirect index	get
  get "/*keyword", to: "redirect#index"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# models/group.rb
class Group < ApplicationRecord
  include VersionUser
  has_paper_trail
  before_destroy :version_history
  after_save :version_history

  has_many :groups_users, dependent: :destroy
  has_many :users, through: :groups_users
  has_many :urls, dependent: :destroy

  has_many :user_contexts, foreign_key: :context_group_id, class_name: "User"

  validates :name, presence: true

  # When a group is destroyed, be sure to reset everyone's contex
  # to their defaults
  before_destroy do |group|
    User.where(context_group_id: group.id).find_each(&:reset_context!)
  end

  # all groups that arent the default group for a user
  scope :not_default, lambda {
    where("id not in ( select default_group_id from users )")
  }

  def user?(user)
    users.exists?(user.id)
  end

  def add_user(user, send_group_change_notifications = false)
    users << user unless users.exists?(user.id)
    groups_users.find_by_user_id(user).update(
      notify_user_changes: send_group_change_notifications
    )
  end

  def remove_user(user)
    users.delete(user)
  end

  def default?
    User.find_by(default_group_id: id).present?
  end

  # Groups for admins will only be one person long and the only user
  # will be an administrator
  def admin?
    users.length == 1 && users.first.admin?
  end

  def version_history
    h = "<b> Current Name: #{name} </b><br/>"
    h.concat "<b>Current Description: #{description}</b><br/>"
    h.concat "<h3>History</h3><hr>"
    versions.each do |v|
      g = v.reify unless v.event.equal? "create"
      h.concat "<b>What Happened: </b> #{v.event} <br/>"
      h.concat "<b>Who Made It: </b>  #{self.class.version_user(v)}<br/>"
      h.concat "<b>Previous Name: </b>  #{g ? g.name : "N/A"}<br/>"
      h.concat "<b>Previous Description: </b>  #{g ? g.description : "N/A"}<br/>"
      h.concat "<b>Date of Change: </b>  #{g ? g.updated_at : "N/A"}<br/>"
      h.concat "<br/><br/>"
    end
    versions.each do |v|
      v.version_history = h
      v.save
    end
  end
end

app/controllers/admin/groups_controller.rb
# controllers/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :ensure_signed_in
  before_action :ensure_is_admin

  def index
    @groups = Group.not_default
    authorize @groups unless @groups.nil?

    respond_to do |format|
      format.html
      format.json { render json: AdminGroupDatatable.new(params, view_context:) }
    end
  end

  def show
    @group = Group.find(params[:id])
    authorize @group unless @group.nil?

    @users = @group.users.map do |user|
      {
        id: user.id,
        uid: user.uid,
        default_group_id: user.default_group_id,
        internet_id: user.internet_id,
        display_name: user.display_name,
        email: user.email,
        admin: user.admin?,
        created_at: user.created_at
      }
    end

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/groups_controller.rb
# controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :ensure_signed_in

  def index
    # Remove the 'yourself' group from your list of groups
    # as you don't need to see it and it's permanent.
    # This group will always be your first group.
    @groups =
      current_user.groups.includes(:users, :urls) - [current_user.default_group]
    @group = Group.new
  end

  def show
    @group_identifier = @group.id
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    @group = Group.new
    @group_identifier = Time.zone.now.to_ms

    @url = Url.find_by(keyword: params[:keyword]) if params[:keyword]
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def edit
    @group_identifier = @group.id
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    @group_identifier = params[:new_identifier]
    @group = Group.new(group_params)
    @group.users << current_user

    @group.urls << Url.find_by(keyword: params[:keyword]) if params[:keyword]

    respond_to do |format|
      if @group.save
        # Since user gets updated (with a new group), a
        # new sign in will be necessary
        sign_in current_user
        format.js { render :create }
        format.json { render json: @group }
      elsif params[:modal]
        format.js { render "groups/new", layout: false }
      else
        format.js { render :edit }
        format.json { render json: { success: false, errors: @group.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @group.update(group_params)
      respond_to do |format|
        format.js { render :update }
        format.json { render json: @group }
      end
    else
      respond_to do |format|
        format.js { render :edit }
        format.json { render json: { success: false, errors: @group.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    return if @group.urls.present?

    if @group.destroy

      # It's possible that the current_user in the DB has changed by
      # removing a group but the user remains unchanged in memory.
      # It will be signified by the context_group_id
      # being the same as the one that was just destroyed (which is
      # not valid), so we need to re-signin the current user
      sign_in current_user if current_user.context_group_id == @group.id

      respond_to do |format|
        format.js   { render layout: false }
        format.json { render json: { success: true, message: "Group deleted." } }
      end
    else
      respond_to do |format|
        format.js   { render layout: false }
        format.json { render json: { success: false, errors: @group.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
    authorize @group unless @group.nil?
    @group_identifier = @group.id
  end

  # Never trust parameters from the scary internet, only permit the allowlist
  # through.
  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/helpers/group_helper.rb
module GroupHelper
  def display_name(group)
    return t('views.urls.index.table.collection_filter.none') if group.default?

    group.name
  end

  def group_names_and_ids_for_select(groups)
    groups.collect do |group|
      [display_name(group), group['id']]
    end.sort_by { |group| [group.first == "No Collection" ? 0 : 1, group.first.downcase] }
  end
end

app/views/groups/_in_row_actions.html.erb
<div class="actions-column">
  <div class="dropdown">
    <button data-toggle="dropdown" class="actions-dropdown-button js-group-actions-dropdown" aria-label="More Actions">
      <i class="fa fa-ellipsis-h">
      </i>
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
      <li>
        <%= link_to t('views.groups.index.table.in_row_actions.members'),
                    group_members_path(group),
                    class: 'btn action-button group-members fa fa-users' %>
      </li>

        <li>
          <%= link_to t('views.groups.index.table.in_row_actions.edit'),
                      edit_group_path(group),
                      class: 'btn action-button edit-group fa fa-pencil', remote: true %>
        </li>
        <li>
          <%= link_to t('views.groups.index.table.in_row_actions.delete'),
                      group_path(group),
                      method: :delete,
                      disabled: group.urls.present?,
                      data: {confirm: t('views.urls.index.table.in_row_actions.delete_confirm', keyword: group.name)},

                      class: 'btn delete-group fa fa-trash-o', remote: true %>
        </li>
    </ul>
  </div>

</div>

app/views/groups/_in_row_errors.html.erb
<div class="error-space"><%= group.errors.full_messages.join('. ') %></div>

app/views/groups/_in_row_form.html.erb
<tr id="group-<%= group_identifier %>" class="table-row-no-padding table-row-edit-main">
  <td colspan=5>
    <div class="center-inline">
      <% is_edit = (defined?(edit) && edit == true) %>
      <div class="z-hero-content">
        <h3 class="tw-text-neutral-900 tw-text-lg tw-mb-4">
          <%= is_edit ? t('views.groups.form.edit.title') : t('views.groups.form.new.title') %>
        </h3>
        <%= form_for_group_admin @admin_view, group do |f| %>
          <%= hidden_field_tag :new_identifier, group_identifier %>
          <div class="tw-flex tw-flex-col md:!tw-flex-row tw-gap-2 md:tw-gap-4 tw-w-fit tw-mx-auto md:tw-justify-center md:tw-items-end">
            <div class="tw-flex tw-flex-col tw-items-start">
              <label class="tw-m-0">Collection Name</label>
              <%= f.text_field :name, class: 'js-new-group-name !tw-m-0', placeholder: t('views.groups.form.placeholders.name') %>
            </div>
            <div class="tw-flex tw-flex-col tw-items-start">
              <label class="tw-m-0">Description</label>
              <%= f.text_field :description, class: 'js-new-group-description !tw-m-0', placeholder: t('views.groups.form.placeholders.description') %>
            </div>
            <button type="submit" class="js-group-submit umn-btn--primary">
              <%= is_edit ? t('views.groups.form.edit.submit') : t('views.groups.form.new.submit')  %>
            </button>
            <button class='umn-btn--secondary cancel-edit'>
              <%= t('views.groups.form.edit.cancel')%>
            </button>
          </div>
        <% end %>
        <%= render 'groups/in_row_errors', group: group %>
      </div>
    </div>
  </td>
</tr>

app/views/groups/_in_row_show.html.erb
<tr id='group-<%= group.id %>'>
  <td>
    <%= link_to group.name, urls_path(collection: group.id), class: 'group-name' %>
    <div class="group-description"><%= group.description %></div>
  </td>
  <td><%= link_to group.users.size, group_members_path(group) %></td>
  <td><%= link_to group.urls.size, urls_path(collection: group.id) %></td>
  <td><%= group.created_at.to_fs(:created_on_formatted)  %></td>
  <td>
    <%= render 'groups/in_row_actions', group: group  %>
  </td>
</tr>

app/views/groups/_new_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel"><%= t('views.groups.new.title', url: display_keyword_url(params[:keyword]) )%></h4>
    </div>
    <%= form_for_group_admin @admin_view, @group do |f| %>

      <div class="modal-body">
          <div class="error-space"><%= @group.errors.full_messages.join('. ') %></div>

            <%= hidden_field_tag :modal, true %>
            <%= hidden_field_tag :new_identifier, @group_identifier %>
            <%= hidden_field_tag :keyword, params[:keyword] %>

              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control js-new-group-name', placeholder: t('views.groups.form.placeholders.name') %>
              <br/>

              <%= f.label :description %>
              <%= f.text_field :description, class: 'form-control js-new-group-description', placeholder: t('views.groups.form.placeholders.description') %>
              <br/>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('views.transfer_requests.new.cancel')%></button>
        <input type="submit" class="btn btn-primary" value="<%= t('views.groups.new.submit') %>" data-confirm="<%= t('views.groups.new.submit_confirm', url: display_keyword_url(params[:keyword]) ) %>" />
      </div>
    <% end %>

  </div>
</div>

app/views/groups/create.js.erb
datatable = $('table.data-table').DataTable()

<% if params[:modal] %>
  $("#index-modal").modal("hide");
  datatable.ajax.reload();
<% else %>
  datatable.rows.add($("<%= escape_javascript(render(partial: 'groups/in_row_show', locals: { group: @group })) %>")); // Add new data
  datatable.columns.adjust().draw(); // Redraw the DataTable
<% end %>

app/views/groups/destroy.js.erb
row = $("tr#group-<%= @group.id %>")
datatable = $('table.data-table').DataTable()
datatable.rows( row ).remove();
datatable.columns.adjust().draw(); // Redraw the DataTable

app/views/groups/edit.js.erb
$(document).find("tr#group-<%= @group_identifier %>").replaceWith(
  $("<%= escape_javascript(render(partial: 'groups/in_row_form', locals: { edit: true, group: @group, group_identifier: @group_identifier })) %>")
);

app/views/groups/index.html.erb
<%- model_class = Group -%>
<!-- header -->
<%= render 'shared/page-header' do %>
  <%= t('views.groups.index.title') %>
<% end %>
<div class="tw-p-4">
  <div class="umn-post-it">
    <section class="tw-max-w-screen-[90em] tw-mx-auto tw-px-4 tw-py-8">
      <div class="groups-table-wrapper">
        <table id="groups-table" class="table user-table table-striped table-bordered data-table tw-table-auto">
          <thead>
            <tr>
              <th class="tw-w-full"><%= t('views.groups.index.table.name') %></th>
              <th><%= t('views.groups.index.table.num_members') %></th>
              <th><%= t('views.groups.index.table.num_links') %></th>
              <th><%= t('views.groups.index.table.created') %></th>
              <th><%= t('views.groups.index.table.actions') %></th>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |group| %>
              <%= render 'in_row_show', group: group %>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to  new_group_path,
             class: 'btn btn-primary btn-xs add-new-group', remote: true  do %>
        <i class="fa fa-plus-circle"></i>
        <%= t("views.groups.index.new_button") %>
      <% end %>
    </section>
  </div>
</div>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

app/views/groups/new.js.erb
<% if params[:modal] %>
  $("#index-modal").html($("<%= escape_javascript(render(partial: 'groups/new_modal')) %>"))
  $("#index-modal").modal()
<% else %>
  $("<%= escape_javascript(render(partial: 'groups/in_row_form', locals: { group: @group, group_identifier: @group_identifier })) %>").appendTo("table tbody");
  $('table tr#new-group-tip').remove();
<% end %>

app/views/groups/update.js.erb
datatable = $('table.data-table').DataTable()
datatable.draw();
row = $("tr#group-<%= @group.id %>")
datatable.rows( row ).remove();
datatable.rows.add($("<%= escape_javascript(render(partial: 'groups/in_row_show', locals: { group: @group })) %>")); // Add new data
datatable.columns.adjust().draw(); // Redraw the DataTable