config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  mount Starburst::Engine => "/starburst"

  # Handle API
  namespace :api do
    namespace :v1 do
      resources :urls, only: %i[create show update]
    end
  end

  # dev routes for cypress
  if Rails.env.development? || Rails.env.test?
    scope path: "/__cypress__", controller: "cypress" do
      post "login", action: "login"
    end
  end

  # Handle Auth
  post "/auth/:provider/callback", to: "sessions#create", as: 'auth_saml_callback'

  # omniauth developer provider uses a GET request
  if Rails.application.config.omniauth_provider == "developer"
    get "/auth/developer/callback", to: "sessions#create"
  end

  get 'auth/saml/metadata' => 'saml_metadata#metadata'

  root "home#index"
  get "shortener", to: "urls#index"

  get "/pages/:page" => "pages#show", :as => :pages

  # This will allow us to run the meat of the app at z.umn.edu/shortener and
  # assume that all other z.umn.edu/:keywords are requests for short urls.
  scope "/shortener" do
    # /	home	index	get
    get "/home", to: "home#index"

    # / user_lookup/:search_terms
    get "/user_lookup/:search_terms", to: "user_lookup#index"

    # faq	faq	index	get
    get "/faq", to: "faq#index", as: "faq"

    # sessions sessions destroy get
    get "/signin", to: "sessions#new"
    get "/signout", to: "sessions#destroy"

    # urls	urls	index	get
    # urls/:id	urls	show	get
    # urls/:id/edit	urls	edit	get
    # urls/new	urls	new	get
    # urls/update	urls	update	post
    # urls/create	urls	create	put
    # urls/destroy	urls	destroy	delete
    resources :urls do
      get "datatable", to: "urls_datatable#index", on: :collection
      get "keyword_filter/(:destination)/(:keyword)",
        on: :collection,
        to: "urls#keyword_filter",
        as: "keyword_filter"
      get "download_qrcode", to: "url_barcodes#show"
      get "csv/click_data", to: "url_csvs#show"
      get "csv/:duration/:time_unit", to: "url_csvs#show_aggregated"
      get "csv/:duration/:time_unit",
        on: :collection,
        to: "url_csvs#show_aggregated",
        as: "csv"
      member do
        patch :note, to: 'urls#update_note'
      end
      patch :note, on: :member, to: 'urls#update_note'
    end

    # transfer_requests	transfer_requests	index	get
    # transfer_requests/new	transfer_requests	new	post
    # transfer_requests/confirm	transfer_requests	confirm	post
    # transfer_requests/create	transfer_requests	create	put
    # transfer_requests/:id/:key/:status	transfer_requests	update	post
    # transfer_requests/:id/show	transfer_requests	show	get
    # transfer_requests/:id/edit	transfer_requests	edit	get
    # transfer_requests/:id/withdraw	transfer_requests	destroy	delete
    resources :transfer_requests do
      post "confirm", on: :member
    end

    resources :move_to_group, only: %i[new create]
    resources :batch_delete, only: %i[new create]

    # groups	groups	index	get
    # groups/:id	groups	show	get
    # groups/:id/edit	groups	edit	get
    # groups/new	groups	new	get
    # groups/update	groups	update	post
    # groups/create	groups	create	put
    # groups/destroy	groups	destroy	delete
    resources :groups do
      # groups/:id/members	group_memberships	index	get
      # groups/:id/members/new	group_memberships	new	get
      # groups/:id/members/create	group_memberships	create	put
      # groups/:id/members/destroy	group_memberships	destroy	delete
      resources :members, only: %i[index new create destroy], controller: "group_memberships" do
        get "new/:search_terms", to: "group_memberships#new", on: :collection
      end
    end

    # users/:id/show	user	show	put
    resources :users, only: [:show]
    resources :lookup_users, only: [:index]
    # api_keys	api_keys	index	get
    # api_keys/new	api_keys	new	get
    # api_keys/:id	api_keys	show	get
    # api_keys/:id/update	api_keys	update	post
    # api_keys/create	api_keys	create	put
    # api_keys/destroy	api_keys	destroy	delete
    resources :api_keys, only: %i[index create] do
      delete "delete", on: :collection
    end

    # group_context/update	group_context	show	get
    resources :group_context, only: [:show]

    namespace :admin do
      # admin/transfer_requests/	admin::transfer_requests	index	get
      # admin/transfer_requests/new	admin::transfer_requests	new	post
      # admin/transfer_requests/confirm	admin::transfer_requests	confirm	post
      # admin/transfer_requests/create	admin::transfer_requests	create	put
      # admin/transfer_requests/:id/show	admin::transfer_requests	show	get
      resources :transfer_requests, only: %i[index new create show] do
        post "confirm", on: :member
      end

      # admin/urls/:search	admin::urls	index	get
      # admin/urls/:id	admin::urls	show	get
      # admin/urls/update	admin::urls	update	post
      # admin/urls/delete	admin::urls	destroy	delete
      # admin/urls/create	admin::urls	create	put
      resources :urls, only: %i[index edit show update destroy create] do
        get "csv/:duration/:time_unit",
            on: :collection,
            to: "url_csvs#show",
            as: "csv"
      end

      # admin/audits/:search	admin::urls	index	get
      # admin/audits/:id	admin::urls	show	get
      resources :audits, only: [:index]

      # admin/groups
      # admin/groups/:id
      # admin/groups/:id/urls
      # admin/groups/:id/members
      resources :groups, only: %i[index show] do
        resources :urls, only: [:index], controller: "group_urls"
        resources :members, only: [:index], controller: "group_members"
      end

      # admin/members/:search	admin::members	index	get
      # admin/members/:id	admin::members	show	get
      # admin/members/delete	admin::members	destroy	delete
      # admin/members/create	admin::members	create	put
      resources :members, only: %i[index new create destroy], controller: "members" do
        get "new/:search_terms", to: "members#new", on: :collection
      end

      # admin/admins	admin::admins	index	get
      # admin/admins/delete	admin::admins	destroy	delete
      # admin/admins/create	admin::admins	create	put
      resources :admins, only: %i[index destroy create]

      resources :announcements, only: %i[index new edit show update destroy create]
    end
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # /:keyword	redirect index	get
  get "/*keyword", to: "redirect#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_to_urls_if_logged_in

  def index; end
end

app/views/home/index.html.erb
<div class="z-bg-umn">
  <div class="tw-relative tw-z-10 tw-max-w-[90em] tw-mx-auto tw-px-8 tw-py-24 tw-text-center">
    <h1 class="tw-text-6xl tw-text-white" data-cy="hero-title">
      <%= t('views.root.hero_text') %>
    </h1>
    <% unless signed_in? %>
      <a class="tw-inline-flex tw-py-4 tw-px-8 tw-bg-umn-gold hover:tw-bg-umn-gold-light tw-text-umn-neutral-900 tw-no-underline hover:tw-text-umn-neutral-900 hover:tw-no-underline tw-my-4" href="<%= signin_path %>">
        <%= t('views.root.hero_button') %>
      </a>
    <% end %>
  </div>
</div>
<div class="tw-max-w-[90em] tw-mx-auto tw-px-4">
  <div class="umn-post-it tw-relative tw-bg-white tw-my-8 tw-p-8 tw-border before:tw-block before:tw-w-24 before:tw-h-5 before:tw-absolute before:tw-bg-umn-gold before:-tw-top-2 before:tw-left-1/2">
    <div class="tw-grid md:tw-grid-cols-2 tw-gap-6 tw-grid-cols-1">
      <div>
        <iframe class="tw-w-full tw-border" width="560" height="315" src="https://www.youtube-nocookie.com/embed/1mvUh2wNCA8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </div>
      <div>
        <h2 class="tw-text-4xl tw-font-semibold">z.umn.edu</h2>
        <div class="tw-space-y-4 tw-text-lg tw-text-umn-neutral-700">
          <p class="">
            Z is a URL shortening service provided
            by <%= link_to 'LATIS', 'http://latis.umn.edu/', target: '_blank' %> and to everyone with a University of Minnesota Internet ID.</p>
          <p><a href="<%= signin_path %>">Sign in</a> to get started.</p>
        </div>
      </div>
    </div>
  </div>